services:
  _defaults:
    autowire: true
    autoconfigure: true

  Vim\ApiSecurity\:
    resource: '../../*'
    exclude: '../../{DependencyInjection}'

  Vim\ApiSecurity\Controller\:
    resource: '../../Controller'
    tags: [ 'controller.service_arguments' ]
